/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_open_SPinterface_SerialPortInterface */

#ifndef _Included_com_open_SPinterface_SerialPortInterface
#define _Included_com_open_SPinterface_SerialPortInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_open_SPinterface_SerialPortInterface
 * Method:    comInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_open_SPinterface_SerialPortInterface_comInit
  (JNIEnv *, jobject, jstring);
/*
 * Class:     com_open_SPinterface_SerialPortInterface
 * Method:    comGet
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_open_SPinterface_SerialPortInterface_comGet
  (JNIEnv *, jobject, jint);
/*
 * Class:     com_open_SPinterface_SerialPortInterface
 * Method:    comWrite
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_open_SPinterface_SerialPortInterface_comWrite
  (JNIEnv *, jobject, jint, jbyteArray, jint);
/*
 * Class:     com_open_SPinterface_SerialPortInterface
 * Method:    comRead
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_open_SPinterface_SerialPortInterface_comRead
  (JNIEnv *, jobject, jint);
/*
 * Class:     com_open_SPinterface_SerialPortInterface
 * Method:    comExt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_open_SPinterface_SerialPortInterface_comExt
  (JNIEnv *, jobject, jint);
#ifdef __cplusplus
}
#endif
#endif
